#!/usr/bin/env python3
"""Builds src/gfs/GfsPalettes.cpp: the model guidance site's (MAG) color bands for the kinds of chart we draw, read from the legends of its images.

The colors of each band are read from the legend swatches in the image (exactly: the legends are flat blocks); the numbers beside them are read by eye (the font is a small bitmap one that
OCR cannot read), written below: for each palette the image it comes from, the LOWER bound of each band from the top swatch of the legend to the bottom (the number printed at the bottom edge
of a swatch is its lower bound), and the factor that brings the legend's units into the units of our fills (inches to millimeters for the precipitation).
Run:  python3 palettes.py <folder of the MAG images> > ../../src/gfs/GfsPalettes.cpp   (needs Pillow; legend.py / crops.py of this folder find the swatches).
"""
import sys
sys.path.insert(0, __file__.rsplit('/', 1)[0])
from crops import crop
PALETTES = {
    # name: (image, lower bounds top to bottom, factor to our units, merge swatches of one color that a line splits)
    'precip':      ('GFS/precip_p24.gif',          [20, 15, 10, 8, 6, 5, 4, 3, 2, 1.5, 1, 0.75, 0.5, 0.25, 0.1, 0.01], 25.4, False),   # inches -> millimeters
    'isotach':     ('GFS/200_wnd_ht.gif',          [200, 150, 130, 110, 90, 70], 1.0, False),                                            # knots
    'radar_rain':  ('HRRR/sim_radar_1km.gif',      [75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 5], 1.0, False),            # dBZ
    'rh':          ('AIGFS/500_rh_ht.gif',         [90, 70], 1.0, True),                                                                 # per cent
    'spread_mslp': ('GEFS-MEAN-SPRD/mslp.gif',     [12, 10, 8, 6, 4, 3, 2, 1, 0.5], 1.0, False),                                         # millibars
    'spread_wind': ('GEFS-MEAN-SPRD/500_wnd.gif',  [30, 26, 22, 18, 14, 10, 8, 6, 4, 2, 1.5, 1], 1.0, False),                            # meters per second
    'helicity':    ('HRRR/helicity_1km.gif',       [700, 600, 500, 400, 300, 250, 200, 150, 100, 50], 1.0, False),                        # m2/s2
    'uh':          ('HRRR/max_updraft_hlcy.gif',   [300, 275, 250, 225, 200, 175, 150, 125, 100, 75, 50, 25], 1.0, False),                # m2/s2
    # these legends print each number at the TOP edge of a swatch (and one more at the very top), so a swatch starts at the number at its bottom edge; the lowest swatch starts at 0
    'prob':        ('GEFS-MEAN-SPRD/prob_cape_500.gif', [90, 80, 70, 60, 50, 40, 30, 20, 10, 5], 1.0, False),                           # per cent (shared by 52 of the images)
    'vis':         ('HRRR/vis.gif',                [9, 8, 7, 6, 5, 4, 3, 2, 1.5, 1, 0.75, 0.5, 0.25, 0.125, 0], 1.0, False),              # statute miles
    'ceiling':     ('HRRR/ceiling.gif',            [45, 40, 35, 30, 25, 20, 15, 10, 5, 1, 0.5, 0.3, 0.1, 0], 1000.0, False),             # thousands of feet -> feet
    'echo_top':    ('HRRR/echo_top.gif',           [65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0], 1.0, False),                   # thousands of feet
    'snowdepth':   ('GEFS-MEAN-SPRD/snodpth_chng_mean.gif', [72, 60, 48, 36, 30, 24, 18, 15, 12, 10, 8, 6, 4, 3, 2, 1, 0.5, 0.1], 2.54, False),   # inches -> centimeters
}
def main(folder):
    out = ['// *****************************************************************************', '// * This file is part of wxqt.  Licensed under the GNU General Public License v3.', '// * See the COPYING file for the full license text.', '// *****************************************************************************', '',
           '// Generated by resourceCreation/mag/palettes.py from the legends of the model guidance site\'s images: do not edit by hand.', '', '#include <map>', '#include <QColor>', '#include "gfs/GfsChart.h"', '',
           'const GfsChart::Ramp * GfsChart::magPalette(const std::string& name) {', '    static const std::map<std::string, Ramp> palettes = [] {', '        std::map<std::string, Ramp> p;']
    import crops
    crops.R = folder.rstrip('/') + '/'
    for name, (image, bounds, factor, merge) in PALETTES.items():
        best = crop(image, '/tmp/_palette.png')
        swatches = []
        for r in best:
            if merge and swatches and swatches[-1][2] == r[2]:
                swatches[-1] = (swatches[-1][0], r[1], r[2])
            else:
                swatches.append(r)
        if len(swatches) != len(bounds):
            raise SystemExit('%s: %d swatches in %s but %d numbers' % (name, len(swatches), image, len(bounds)))
        out.append('        {   // %s: %d bands, from %s' % (name, len(bounds), image))
        out.append('            Ramp r;')
        out.append('            r.banded = true;')
        for (y0, y1, rgb), low in reversed(list(zip(swatches, bounds))):   # lowest band first
            out.append('            r.stops.push_back({%s, QColor{%d, %d, %d}});' % (repr(round(low * factor, 6)), rgb[0], rgb[1], rgb[2]))
        out.append('            p["%s"] = r;' % name)
        out.append('        }')
    out += ['        return p;', '    }();', '    const auto found = palettes.find(name);', '    return found == palettes.end() ? nullptr : &found->second;', '}']
    print('\n'.join(out))
if __name__ == '__main__':
    main(sys.argv[1])
