#!/usr/bin/env python3
# Generates src/sounding/SoundingSarsData.cpp from SHARPpy's SARS databases (BSD licence, see docs/sharppy-notice.md):
#   sars_supercell.txt (Rich Thompson, SPC) and sars_hail.txt (Ryan Jewell, SPC), both from
#   https://github.com/sharppy/SHARPpy/tree/master/sharppy/databases
# Usage: python3 resourceCreation/sars/gen_sars_data.py   (from the repository root)
import os

here = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(here, '..', '..', 'src', 'sounding', 'SoundingSarsData.cpp')


def rows(name, columns):
    result = []
    with open(os.path.join(here, name)) as handle:
        next(handle)   # header
        for line in handle:
            line = line.split('%%%%')[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < columns:
                continue
            result.append(parts)
    return result


supercell = rows('sars_supercell.txt', 15)
hail = rows('sars_hail.txt', 13)
with open(out_path, 'w') as out:
    out.write('// Generated by resourceCreation/sars/gen_sars_data.py from the SARS databases in SHARPpy (BSD licence,\n')
    out.write('// docs/sharppy-notice.md): sars_supercell.txt (Rich Thompson, NOAA SPC) and sars_hail.txt (Ryan Jewell, NOAA SPC).\n')
    out.write('// Do not edit by hand.\n\n#include "sounding/SoundingSars.h"\n\nnamespace SoundingSars {\n')
    out.write('const std::vector<SupercellRecord>& supercellDatabase() {\n    static const std::vector<SupercellRecord> data{\n')
    for p in supercell:
        # id, category, mlcape, mllcl, 0-1 srh, 0-6 shear, 500 temp, 7-5 lapse rate, 0-3 shear, 0-9 shear, 0-3 srh
        out.write('        {"%s", %s, %s, %s, %s, %s, %s, %s, %s, %s, %s},\n' % (p[0], p[1], p[3], p[5], p[6], p[7], p[9], p[11], p[12], p[13], p[14]))
    out.write('    };\n    return data;\n}\n\n')
    out.write('const std::vector<HailRecord>& hailDatabase() {\n    static const std::vector<HailRecord> data{\n')
    for p in hail:
        # id, report size, mucape, mu mixing ratio, 500 temp, 7-5 lapse rate, 0-3 shear, 0-6 shear, 0-9 shear, 0-3 srh
        out.write('        {"%s", %s, %s, %s, %s, %s, %s, %s, %s, %s},\n' % (p[0], p[2], p[3], p[4], p[5], p[7], p[9], p[10], p[11], p[12]))
    out.write('    };\n    return data;\n}\n}\n')
print(len(supercell), 'supercell rows,', len(hail), 'hail rows')
